"""
LLM 提供商管理模块

每个角色（CHAT / VISION / ...）独立一组 .env 字段，互不干扰。
新增角色：只需 .env 加一组 {ROLE}_* 字段，再加一行 `def get_xxx_llm()`。
"""

import asyncio
import time
from typing import Optional, Any, Iterator, AsyncIterator, Sequence, Union

import httpx
from langchain_core.language_models import BaseChatModel
from langchain_core.messages import AIMessageChunk
from langchain_core.outputs import ChatGenerationChunk
from langchain_core.tools import BaseTool
from langchain_openai import ChatOpenAI
from loguru import logger

from app.langchain.config import (
    ConfigError,
    RoleConfig,
    has_role,
    langchain_config,
    load_role,
)


class ThinkingTruncatedError(RuntimeError):
    """LLM 思考阶段连续被 max_tokens 截断，超过最大重试次数。"""


_THINKING_RETRIES = 3


def _file_block_to_placeholder(block: dict) -> str:
    """把 OpenAI 格式的 file 内容块转成文本占位符，保留文件名 / URL 供模型引用。"""
    f = block.get("file") or {}
    name = f.get("filename") or ""
    if name == "LC_AUTOGENERATED":
        name = ""
    ref = f.get("file_data") or f.get("file_id") or ""
    if isinstance(ref, str) and ref.startswith("data:"):
        # base64 data URI 不写进提示，避免撑爆上下文
        ref = ""
    parts = [p for p in (name, ref) if p]
    desc = "，".join(parts) if parts else "未知文件"
    return f"[附件文件: {desc}]"


def _sanitize_dashscope_payload(payload: dict, base_url: Optional[str]) -> None:
    """DashScope 的 chat/completions（GPT3Message schema）不支持 OpenAI 的 file 内容块。

    MCP 工具（如 WebSearch）返回的资源链接会被 langchain 规范成
    ``{'type': 'file', 'file': {'file_data': 'http://...', ...}}`` 落入 ToolMessage，
    一旦进入 checkpoint 历史，之后每一轮请求都会被 DashScope 400 拒绝。
    这里在发请求前把 file 块替换成文本占位块，彻底规避该问题。
    """
    base = (base_url or "").lower()
    if "dashscope" not in base and "aliyuncs" not in base:
        return
    for msg in payload.get("messages") or []:
        content = msg.get("content")
        if not isinstance(content, list):
            continue
        new_content = []
        changed = False
        for block in content:
            if isinstance(block, dict) and block.get("type") == "file":
                new_content.append({"type": "text", "text": _file_block_to_placeholder(block)})
                changed = True
            else:
                new_content.append(block)
        if changed:
            msg["content"] = new_content


# ── DashScope 偶发 URL 拉取失败容错 ───────────────────────────────────────────
# 多模态请求中 DashScope 服务端要回源拉取图片/视频 URL，该拉取会偶发失败
# （实测约 5%），400 报错文案却误导为 "URL does not appear to be valid"。
# 长链路 agent 每轮模型调用都会重发历史里全部图片 URL，单轮 7+ 次调用时命中
# 一次即整个任务失败（历史 case：首条带图消息成功、工具调用后第二次调用 400）。
# 策略：仅原样重试（下一次通常即恢复），重试 3 次后单点失败率降至 ~0.0006%；
# 重试耗尽按原异常抛出，不做 base64 内联兜底（会引入上下文膨胀等新问题）。
_URL_FETCH_ERR_MARK = "does not appear to be valid"
_URL_FETCH_RETRIES = 3
_URL_FETCH_RETRY_DELAY = 2.0


def _is_url_fetch_error(exc: BaseException) -> bool:
    return _URL_FETCH_ERR_MARK in str(exc)


class AgentCompatibleChat(ChatOpenAI):
    """
    通用 OpenAI 兼容接口包装。

    - DashScope thinking 模式不支持 tool_choice="any"/"required"，自动降级为 "auto"
    - finish_reason=length 时：若仍在思考阶段则静默重试（最多 3 次），否则保留输出并附提示
    - DashScope 偶发 URL 拉取 400：原样重试（见 _URL_FETCH_* 说明），耗尽后按原异常抛出
    - thinking 模式下仅回传最近一条 assistant 的 reasoning_content（DashScope 多轮 tool_call 要求；历史思考不回传，避免 payload 二次方膨胀）
    - context_window：模型上下文窗口大小（token），供 deepagents SummarizationMiddleware 计算压缩阈值
    """

    context_window: Optional[int] = None

    def _resolve_model_profile(self):
        if self.context_window:
            return {"max_input_tokens": self.context_window}
        return None

    def bind_tools(
        self,
        tools: Sequence[Union[dict[str, Any], type, BaseTool]],
        *,
        tool_choice: Optional[Union[dict, str, bool]] = None,
        **kwargs: Any,
    ) -> "AgentCompatibleChat":
        if "dashscope" in (self.openai_api_base or "") and tool_choice not in (None, "auto", "none", False):
            tool_choice = "auto"
        return super().bind_tools(tools, tool_choice=tool_choice, **kwargs)

    def _convert_chunk_to_generation_chunk(self, chunk, default_chunk_class, base_generation_info):
        gen_chunk = super()._convert_chunk_to_generation_chunk(chunk, default_chunk_class, base_generation_info)
        if gen_chunk is None:
            return None
        try:
            choices = chunk.get("choices") or chunk.get("chunk", {}).get("choices") or []
            if choices:
                delta = choices[0].get("delta") or {}
                rc = delta.get("reasoning_content") or delta.get("reasoning")
                if rc:
                    gen_chunk.message.additional_kwargs["reasoning_content"] = rc
        except (AttributeError, KeyError, IndexError, TypeError):
            pass
        return gen_chunk

    def _resilient_stream(self, messages, stop=None, run_manager=None, **kwargs) -> Iterator[ChatGenerationChunk]:
        """同步流：DashScope 偶发 URL 拉取 400 时原样重试，耗尽后按原异常抛出。"""
        last_exc: Optional[BaseException] = None
        yielded = False
        for i in range(_URL_FETCH_RETRIES + 1):
            try:
                for chunk in super()._stream(messages, stop=stop, run_manager=run_manager, **kwargs):
                    yielded = True
                    yield chunk
                return
            except Exception as e:
                if yielded or not _is_url_fetch_error(e):
                    raise
                last_exc = e
                if i < _URL_FETCH_RETRIES:
                    logger.warning(f"[LLM] URL 拉取偶发失败，{int(_URL_FETCH_RETRY_DELAY)}s 后重试 {i + 1}/{_URL_FETCH_RETRIES}：{str(e)[:120]}")
                    time.sleep(_URL_FETCH_RETRY_DELAY)
        raise last_exc

    async def _resilient_astream(self, messages, stop=None, run_manager=None, **kwargs) -> AsyncIterator[ChatGenerationChunk]:
        """异步流：DashScope 偶发 URL 拉取 400 时原样重试，耗尽后按原异常抛出。"""
        last_exc: Optional[BaseException] = None
        yielded = False
        for i in range(_URL_FETCH_RETRIES + 1):
            try:
                async for chunk in super()._astream(messages, stop=stop, run_manager=run_manager, **kwargs):
                    yielded = True
                    yield chunk
                return
            except Exception as e:
                if yielded or not _is_url_fetch_error(e):
                    raise
                last_exc = e
                if i < _URL_FETCH_RETRIES:
                    logger.warning(f"[LLM] URL 拉取偶发失败，{int(_URL_FETCH_RETRY_DELAY)}s 后重试 {i + 1}/{_URL_FETCH_RETRIES}：{str(e)[:120]}")
                    await asyncio.sleep(_URL_FETCH_RETRY_DELAY)
        raise last_exc

    def _stream(self, messages, stop=None, run_manager=None, **kwargs) -> Iterator[ChatGenerationChunk]:
        last_chunk = None
        for chunk in self._resilient_stream(messages, stop=stop, run_manager=run_manager, **kwargs):
            last_chunk = chunk
            yield chunk
        if last_chunk is not None and (last_chunk.generation_info or {}).get("finish_reason") == "length":
            logger.warning("[LLM] 同步流输出被截断（finish_reason=length）")

    def _get_request_payload(self, input_, *, stop=None, **kwargs):
        payload = super()._get_request_payload(input_, stop=stop, **kwargs)
        if "max_completion_tokens" in payload:
            payload["max_tokens"] = payload["max_completion_tokens"]

        from langchain_core.messages import AIMessage

        if isinstance(input_, list):
            ai_msgs = [m for m in input_ if isinstance(m, AIMessage)]
            assistant_dicts = [m for m in (payload.get("messages") or []) if m.get("role") == "assistant"]
            # 只回传【最近一条】assistant 消息的 reasoning_content：
            # DashScope 多轮 tool_call 要求思考字段在场，但历史思考文本对后续推理毫无价值。
            # 此前全量重发导致 payload 随轮数接近二次方增长（60 轮工具调用可累积 10 万+ 字符冗余），
            # 是 agent 逐轮变慢的主因之一。若某 provider 因缺少更早的 reasoning 报 400，
            # 可退化为「保留最近 N 条」，不要恢复全量重发。
            if ai_msgs and assistant_dicts:
                rc = (ai_msgs[-1].additional_kwargs or {}).get("reasoning_content")
                if rc and "reasoning_content" not in assistant_dicts[-1]:
                    assistant_dicts[-1]["reasoning_content"] = rc

        # DashScope 不支持 file 内容块（MCP 资源链接会被 langchain 规范成 file 块，
        # 落入 checkpoint 后每轮都会 400），发请求前统一替换为文本占位符
        _sanitize_dashscope_payload(payload, self.openai_api_base)

        # kimi-k3 只接受 temperature=0.6，代码中多处硬编码了其他值（0.1/0.2/0.7），
        # 在此统一拦截，避免 400 错误
        _model = (payload.get("model") or "").lower()
        if "kimi-k3" in _model and payload.get("temperature") != 0.6:
            logger.warning(f"[LLM] {_model} 仅支持 temperature=0.6，已将 {payload.get('temperature')} 强制覆盖")
            payload["temperature"] = 0.6

        # 原始请求 payload 日志（DEBUG 级，多轮对话消息数量是性能关键指标）
        import json as _json

        msgs = payload.get("messages", [])
        msg_count = len(msgs)
        total_chars = sum(len(_json.dumps(m, ensure_ascii=False)) for m in msgs)
        # logger.debug(
        #     f"[LLM payload] model={payload.get('model')} messages={msg_count} "
        #     f"total_chars={total_chars} max_tokens={payload.get('max_tokens')}"
        # )
        # logger.debug(f"[LLM payload raw]\n{_json.dumps(payload, ensure_ascii=False, indent=2)}")
        return payload

    async def _astream(self, messages, stop=None, run_manager=None, **kwargs) -> AsyncIterator[ChatGenerationChunk]:
        # thinking 阶段（无 content，仅 reasoning_content）需缓冲以便截断重试；
        # 一旦进入输出阶段（出现首个非空 content），立即把缓冲吐出并切到直通模式逐 chunk yield，
        # 否则前端会等到模型完整生成后才一次性看到全部内容，等同于非流式。
        for attempt in range(_THINKING_RETRIES + 1):
            buffered: list[ChatGenerationChunk] = []
            last_chunk: Optional[ChatGenerationChunk] = None
            flushed = False

            async for chunk in self._resilient_astream(messages, stop=stop, run_manager=run_manager, **kwargs):
                last_chunk = chunk
                if flushed:
                    yield chunk
                    continue
                if getattr(chunk.message, "content", ""):
                    for c in buffered:
                        yield c
                    buffered = []
                    flushed = True
                    yield chunk
                else:
                    buffered.append(chunk)

            if last_chunk is None:
                return

            reason = (last_chunk.generation_info or {}).get("finish_reason")
            still_thinking = not flushed

            if reason == "length" and still_thinking:
                if attempt < _THINKING_RETRIES:
                    logger.warning(f"[LLM] 思考阶段被截断，第 {attempt + 1}/{_THINKING_RETRIES} 次重试...")
                    continue
                raise ThinkingTruncatedError(f"LLM 思考阶段连续截断 {_THINKING_RETRIES} 次，请调大 *_MAX_TOKENS。")

            if reason == "length":
                if not flushed:
                    for c in buffered:
                        yield c
                logger.warning("[LLM] 输出阶段被截断（finish_reason=length）")
                yield ChatGenerationChunk(message=AIMessageChunk(content="\n\n[注意：上述输出因达到 token 上限而被截断，请根据已有内容继续完成任务。]"))
                return

            if not flushed:
                for c in buffered:
                    yield c
            return


# Ollama thinking 模式实测最优反重复参数（tests/test_ollama_thinking_loop.py 压测得出）
_OLLAMA_DEFAULTS = {
    "temperature": 0.6,
    "frequency_penalty": 0.5,
    "presence_penalty": 0.3,
}


def _is_ollama(cfg: RoleConfig) -> bool:
    """约定 api_key=ollama 即视为 Ollama 端点。"""
    return (cfg.api_key or "").lower() == "ollama"


def _build_thinking_extra_body(cfg: RoleConfig, thinking: bool) -> dict:
    """根据 base_url + model 选择对应 provider 的 thinking 参数格式。"""
    base = (cfg.base_url or "").lower()
    model = (cfg.model or "").lower()

    if _is_ollama(cfg):
        return {"think": thinking}
    # kimi-k3 不支持 enable_thinking=false，携带该参数会触发误导性 400
    # "invalid temperature: only 0.6 is allowed"；直接跳过，不发送 thinking 相关字段
    if "kimi-k3" in model:
        return {}
    if ("dashscope" in base or "aliyuncs" in base) and ("deepseek" in model or "claude" in model):
        return {"thinking": {"type": "enabled" if thinking else "disabled"}}
    if "dashscope" in base or "aliyuncs" in base:
        return {"enable_thinking": thinking}
    if "anthropic" in base or "claude" in model:
        return {"thinking": {"type": "enabled" if thinking else "disabled"}}
    return {"enable_thinking": thinking}


def _build_chat(
    cfg: RoleConfig,
    *,
    model_override: Optional[str] = None,
    temperature_override: Optional[float] = None,
    **extra_kwargs: Any,
) -> AgentCompatibleChat:
    """根据 RoleConfig 构造 Chat 模型实例。所有 chat-like 角色共用此函数。"""
    is_ollama = _is_ollama(cfg)

    # temperature：函数参数 > 角色 .env > Ollama 推荐 > 全局 DEFAULT_TEMPERATURE
    if temperature_override is not None:
        temperature = temperature_override
    elif cfg.temperature is not None:
        temperature = cfg.temperature
    elif is_ollama:
        temperature = _OLLAMA_DEFAULTS["temperature"]
    else:
        temperature = langchain_config.DEFAULT_TEMPERATURE

    init_kwargs: dict = dict(
        model=model_override or cfg.model,
        base_url=cfg.base_url,
        api_key=cfg.api_key,
        temperature=temperature,
        timeout=httpx.Timeout(
            connect=30.0,
            read=float(langchain_config.LLM_REQUEST_TIMEOUT),
            write=30.0,
            pool=30.0,
        ),
        max_retries=10,
        streaming=True,
        stream_chunk_timeout=None,  # 禁用 per-chunk 超时，依赖 httpx read timeout 兜底
        **extra_kwargs,
    )
    if cfg.max_tokens is not None:
        init_kwargs["max_tokens"] = cfg.max_tokens
    if cfg.context_window is not None:
        init_kwargs["context_window"] = cfg.context_window

    if cfg.frequency_penalty is not None:
        init_kwargs["frequency_penalty"] = cfg.frequency_penalty
    elif is_ollama:
        init_kwargs["frequency_penalty"] = _OLLAMA_DEFAULTS["frequency_penalty"]

    if cfg.presence_penalty is not None:
        init_kwargs["presence_penalty"] = cfg.presence_penalty
    elif is_ollama:
        init_kwargs["presence_penalty"] = _OLLAMA_DEFAULTS["presence_penalty"]

    if cfg.headers:
        import json as _json

        init_kwargs["default_headers"] = _json.loads(cfg.headers)
    if cfg.thinking is not None:
        init_kwargs["extra_body"] = _build_thinking_extra_body(cfg, cfg.thinking)

    # 计费回调：每次 LLM 调用结束后自动写 agent_usage_log。
    # 失败安全（callback 内部已包 try/except），不影响业务调用。
    from app.langchain.billing.callback import BillingCallbackHandler

    init_kwargs.setdefault("callbacks", []).append(
        BillingCallbackHandler(
            role=cfg.role,
            model=model_override or cfg.model,
            base_url=cfg.base_url,
        )
    )

    return AgentCompatibleChat(**init_kwargs)


# ── 角色工厂（新增角色就在这里加一行） ───────────────────────────────────────

_chat_singleton: Optional[AgentCompatibleChat] = None
_smart_cmp_llm_singleton: Optional[AgentCompatibleChat] = None


def get_llm(
    model: Optional[str] = None,
    temperature: Optional[float] = None,
    **kwargs,
) -> BaseChatModel:
    """主对话 LLM。读取 .env 中 CHAT_* 字段。"""
    kwargs.pop("provider", None)  # 兼容旧调用
    global _chat_singleton

    cfg = load_role("CHAT")
    if _chat_singleton is None or model is not None or temperature is not None or kwargs:
        instance = _build_chat(cfg, model_override=model, temperature_override=temperature, **kwargs)
        if model is None and temperature is None and not kwargs:
            _chat_singleton = instance
        return instance
    return _chat_singleton


def get_smart_comparison_llm() -> BaseChatModel:
    """Smart比对专用 LLM：基于 CHAT 角色，强制 thinking=True、max_tokens=16000，忽略 env 中对应配置。"""
    import dataclasses

    global _smart_cmp_llm_singleton
    if _smart_cmp_llm_singleton is None:
        cfg = dataclasses.replace(load_role("CHAT"), thinking=False, max_tokens=16000)
        _smart_cmp_llm_singleton = _build_chat(cfg)
    return _smart_cmp_llm_singleton


# 按块 chat LLM 单例（按角色模型配置用）：块名 → 实例。
# 独立于 _chat_singleton（它跟随全局激活块重定向）；clear_model_caches() 会一并清空
# （admin 改块凭据后按角色单例必须失效）。
_block_llm_singletons: dict[str, AgentCompatibleChat] = {}


def get_chat_llm_for_block(block_key: str) -> BaseChatModel:
    """按指定预设块构建 chat LLM（按角色模型配置；按块单例）。

    不走 "CHAT" 激活块重定向——load_role(块名) 直接读该块的物化 env。
    块配置残缺（ConfigError）时回退全局激活块（get_llm()），不打断链路。
    Billing 归因 role 为块名。
    """
    key = block_key.upper()
    instance = _block_llm_singletons.get(key)
    if instance is not None:
        return instance
    try:
        cfg = load_role(key)
    except ConfigError:
        logger.warning(f"[llm_providers] chat 块 {key} 配置不完整，回退全局激活块")
        return get_llm()
    instance = _build_chat(cfg)
    _block_llm_singletons[key] = instance
    return instance


def get_vision_llm(**kwargs) -> Optional[BaseChatModel]:
    """视觉 LLM。读取 .env 中 VISION_* 字段；未配置返回 None。"""
    if not has_role("VISION"):
        return None
    return _build_chat(load_role("VISION"), **kwargs)


# 兼容旧导入：保留 LLMProvider 枚举（外部 import 仍能拿到，但不再起作用）
def __getattr__(name: str):
    if name == "LLMProvider":
        from enum import Enum

        return Enum("LLMProvider", {"OLLAMA": "ollama", "DASHSCOPE": "dashscope"})
    raise AttributeError(name)
